apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 8;
    }
    http {
        server {
            listen 80;
            
            # Enable NGINX status page for metrics
            location /nginx_status {
                stub_status on;
                access_log off;
                allow all;
            }
            
            # Your app
            location / {
                root /usr/share/nginx/html;
                index index.html;
                try_files $uri $uri/ /index.html;
            }
        }
    }
